CREATE DATABASE gestorEmpleadosNidaeAsrih;
-- DROP DATABASE gestorEmpleadosNidaeAsrih;
use `gestorEmpleadosNidaeAsrih`;

CREATE TABLE TRABAJADOR(
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL,
PUESTO VARCHAR(50) NOT NULL,
SALARIO INTEGER NOT NULL,
FECHA DATE NOT NULL
);